version: "3"

services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile

  cardservice:
    build:
      context: ./CardService
      dockerfile: Dockerfile

  storeservice:
    build:
      context: ./StoreService
      dockerfile: Dockerfile

  staticservice:
    build:
      context: ./StaticService
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Port pour le reverse proxy NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Configuration NGINX
    depends_on:
      - userservice
      - cardservice
      - storeservice
      - staticservice
