version: "3"

services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  superservice:
    build:
      context: ./SuperService
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8084:8080"

  staticservice:
    build:
      context: ./StaticService
      dockerfile: Dockerfile
    ports:
      - "3000:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Port pour le reverse proxy NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Configuration NGINX
    depends_on:
      - userservice
      - staticservice
      - superservice
      - notificationservice
