version: "3"

services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  staticservice:
    build:
      context: ./StaticService
      dockerfile: Dockerfile
    ports:
      - "3000:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Port pour le reverse proxy NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Configuration NGINX
    depends_on:
      - userservice
      - staticservice
