# Utiliser l'image Nginx officielle comme base
FROM nginx:1.21

# Copier votre fichier de configuration personnalisé nginx.conf dans le conteneur
COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port 80
EXPOSE 80